require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstructorcoursesController do

  # This should return the minimal set of attributes required to create a valid
  # Instructorcourse. As you add validations to Instructorcourse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "instructoremail" => "MyString", "coursename" => "MyString", "coursecode"=>"MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InstructorcoursesController. Be sure to keep this updated too.
  let(:valid_session) { {} }
=begin
  describe "GET index" do
    it "assigns all instructorcourses as @instructorcourses" do
      instructorcourse = Instructorcourse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:instructorcourses).should eq([instructorcourse])
    end
  end

  describe "GET show" do
    it "assigns the requested instructorcourse as @instructorcourse" do
      instructorcourse = Instructorcourse.create! valid_attributes
      get :show, {:id => instructorcourse.to_param}, valid_session
      assigns(:instructorcourse).should eq(instructorcourse)
    end
  end

  describe "GET new" do
    it "assigns a new instructorcourse as @instructorcourse" do
      get :new, {}, valid_session
      assigns(:instructorcourse).should be_a_new(Instructorcourse)
    end
  end

  describe "GET edit" do
    it "assigns the requested instructorcourse as @instructorcourse" do
      instructorcourse = Instructorcourse.create! valid_attributes
      get :edit, {:id => instructorcourse.to_param}, valid_session
      assigns(:instructorcourse).should eq(instructorcourse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Instructorcourse" do
        expect {
          post :create, {:instructorcourse => valid_attributes}, valid_session
        }.to change(Instructorcourse, :count).by(1)
      end

      it "assigns a newly created instructorcourse as @instructorcourse" do
        post :create, {:instructorcourse => valid_attributes}, valid_session
        assigns(:instructorcourse).should be_a(Instructorcourse)
        assigns(:instructorcourse).should be_persisted
      end

      it "redirects to the created instructorcourse" do
        post :create, {:instructorcourse => valid_attributes}, valid_session
        response.should redirect_to(Instructorcourse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instructorcourse as @instructorcourse" do
        # Trigger the behavior that occurs when invalid params are submitted
        Instructorcourse.any_instance.stub(:save).and_return(false)
        post :create, {:instructorcourse => { "instructoremail" => "invalid value" }}, valid_session
        assigns(:instructorcourse).should be_a_new(Instructorcourse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Instructorcourse.any_instance.stub(:save).and_return(false)
        post :create, {:instructorcourse => { "instructoremail" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instructorcourse" do
        instructorcourse = Instructorcourse.create! valid_attributes
        # Assuming there are no other instructorcourses in the database, this
        # specifies that the Instructorcourse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Instructorcourse.any_instance.should_receive(:update_attributes).with({ "instructoremail" => "MyString" })
        put :update, {:id => instructorcourse.to_param, :instructorcourse => { "instructoremail" => "MyString" }}, valid_session
      end

      it "assigns the requested instructorcourse as @instructorcourse" do
        instructorcourse = Instructorcourse.create! valid_attributes
        put :update, {:id => instructorcourse.to_param, :instructorcourse => valid_attributes}, valid_session
        assigns(:instructorcourse).should eq(instructorcourse)
      end

      it "redirects to the instructorcourse" do
        instructorcourse = Instructorcourse.create! valid_attributes
        put :update, {:id => instructorcourse.to_param, :instructorcourse => valid_attributes}, valid_session
        response.should redirect_to(instructorcourse)
      end
    end

    describe "with invalid params" do
      it "assigns the instructorcourse as @instructorcourse" do
        instructorcourse = Instructorcourse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Instructorcourse.any_instance.stub(:save).and_return(false)
        put :update, {:id => instructorcourse.to_param, :instructorcourse => { "instructoremail" => "invalid value" }}, valid_session
        assigns(:instructorcourse).should eq(instructorcourse)
      end

      it "re-renders the 'edit' template" do
        instructorcourse = Instructorcourse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Instructorcourse.any_instance.stub(:save).and_return(false)
        put :update, {:id => instructorcourse.to_param, :instructorcourse => { "instructoremail" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instructorcourse" do
      instructorcourse = Instructorcourse.create! valid_attributes
      expect {
        delete :destroy, {:id => instructorcourse.to_param}, valid_session
      }.to change(Instructorcourse, :count).by(-1)
    end

    it "redirects to the instructorcourses list" do
      instructorcourse = Instructorcourse.create! valid_attributes
      delete :destroy, {:id => instructorcourse.to_param}, valid_session
      response.should redirect_to(instructorcourses_url)
    end
  end
=end

end
