require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Instructor1sController do

  # This should return the minimal set of attributes required to create a valid
  # Instructor1. As you add validations to Instructor1, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Instructor1sController. Be sure to keep this updated too.
  let(:valid_session) { {} }

	it "invalid signup info" do
		get 'new'
		expect do
			post 'create', instructor1s: {Full_Name:"",
							email:"invalid@invalid",
							password:"456789"}
		end.to_not change{Instructor1.count}
		expect(response).to render_template(:new)
	end

=begin
  describe "GET index" do
    it "assigns all instructor1s as @instructor1s" do
      instructor1 = Instructor1.create! valid_attributes
      get :index, {}, valid_session
      assigns(:instructor1s).should eq([instructor1])
    end
  end

  describe "GET show" do
    it "assigns the requested instructor1 as @instructor1" do
      instructor1 = Instructor1.create! valid_attributes
      get :show, {:id => instructor1.to_param}, valid_session
      assigns(:instructor1).should eq(instructor1)
    end
  end

  describe "GET new" do
    it "assigns a new instructor1 as @instructor1" do
      get :new, {}, valid_session
      assigns(:instructor1).should be_a_new(Instructor1)
    end
  end

  describe "GET edit" do
    it "assigns the requested instructor1 as @instructor1" do
      instructor1 = Instructor1.create! valid_attributes
      get :edit, {:id => instructor1.to_param}, valid_session
      assigns(:instructor1).should eq(instructor1)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Instructor1" do
        expect {
          post :create, {:instructor1 => valid_attributes}, valid_session
        }.to change(Instructor1, :count).by(1)
      end

      it "assigns a newly created instructor1 as @instructor1" do
        post :create, {:instructor1 => valid_attributes}, valid_session
        assigns(:instructor1).should be_a(Instructor1)
        assigns(:instructor1).should be_persisted
      end

      it "redirects to the created instructor1" do
        post :create, {:instructor1 => valid_attributes}, valid_session
        response.should redirect_to(Instructor1.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instructor1 as @instructor1" do
        # Trigger the behavior that occurs when invalid params are submitted
        Instructor1.any_instance.stub(:save).and_return(false)
        post :create, {:instructor1 => { "email" => "invalid value" }}, valid_session
        assigns(:instructor1).should be_a_new(Instructor1)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Instructor1.any_instance.stub(:save).and_return(false)
        post :create, {:instructor1 => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instructor1" do
        instructor1 = Instructor1.create! valid_attributes
        # Assuming there are no other instructor1s in the database, this
        # specifies that the Instructor1 created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Instructor1.any_instance.should_receive(:update_attributes).with({ "email" => "MyString" })
        put :update, {:id => instructor1.to_param, :instructor1 => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested instructor1 as @instructor1" do
        instructor1 = Instructor1.create! valid_attributes
        put :update, {:id => instructor1.to_param, :instructor1 => valid_attributes}, valid_session
        assigns(:instructor1).should eq(instructor1)
      end

      it "redirects to the instructor1" do
        instructor1 = Instructor1.create! valid_attributes
        put :update, {:id => instructor1.to_param, :instructor1 => valid_attributes}, valid_session
        response.should redirect_to(instructor1)
      end
    end

    describe "with invalid params" do
      it "assigns the instructor1 as @instructor1" do
        instructor1 = Instructor1.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Instructor1.any_instance.stub(:save).and_return(false)
        put :update, {:id => instructor1.to_param, :instructor1 => { "email" => "invalid value" }}, valid_session
        assigns(:instructor1).should eq(instructor1)
      end

      it "re-renders the 'edit' template" do
        instructor1 = Instructor1.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Instructor1.any_instance.stub(:save).and_return(false)
        put :update, {:id => instructor1.to_param, :instructor1 => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instructor1" do
      instructor1 = Instructor1.create! valid_attributes
      expect {
        delete :destroy, {:id => instructor1.to_param}, valid_session
      }.to change(Instructor1, :count).by(-1)
    end

    it "redirects to the instructor1s list" do
      instructor1 = Instructor1.create! valid_attributes
      delete :destroy, {:id => instructor1.to_param}, valid_session
      response.should redirect_to(instructor1s_url)
    end
  end
=end

end
